// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates taglines for apps using an AI-powered tool.
 *
 * - generateAppTaglines - A function that generates taglines for an app.
 * - GenerateAppTaglinesInput - The input type for the generateAppTaglines function.
 * - GenerateAppTaglinesOutput - The return type for the generateAppTaglines function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAppTaglinesInputSchema = z.object({
  appName: z.string().describe('The name of the app.'),
  appDescription: z.string().describe('A brief description of the app.'),
  appCategory: z.string().describe('The category of the app (e.g., saving money, organization, health, etc.).'),
});
export type GenerateAppTaglinesInput = z.infer<typeof GenerateAppTaglinesInputSchema>;

const GenerateAppTaglinesOutputSchema = z.object({
  taglines: z.array(z.string()).describe('An array of generated taglines for the app.'),
});
export type GenerateAppTaglinesOutput = z.infer<typeof GenerateAppTaglinesOutputSchema>;

export async function generateAppTaglines(input: GenerateAppTaglinesInput): Promise<GenerateAppTaglinesOutput> {
  return generateAppTaglinesFlow(input);
}

const generateAppTaglinesPrompt = ai.definePrompt({
  name: 'generateAppTaglinesPrompt',
  input: {schema: GenerateAppTaglinesInputSchema},
  output: {schema: GenerateAppTaglinesOutputSchema},
  prompt: `You are an AI-powered tagline generator specializing in creating catchy and effective taglines for apps.

  Generate five taglines for the following app:

  App Name: {{appName}}
  App Description: {{appDescription}}
  App Category: {{appCategory}}

  The taglines should be creative, concise, and relevant to the app's purpose and target audience. The taglines should be different from each other.
  Format the output as a JSON array of strings. Do not include any other text.`,
});

const generateAppTaglinesFlow = ai.defineFlow(
  {
    name: 'generateAppTaglinesFlow',
    inputSchema: GenerateAppTaglinesInputSchema,
    outputSchema: GenerateAppTaglinesOutputSchema,
  },
  async input => {
    const {output} = await generateAppTaglinesPrompt(input);
    return output!;
  }
);
